#!/bin/sh
MINUTE=`date '+%S'`

if test -f /home/bitnami/change-password.sh ; then
  mv /home/bitnami/change-password.sh /home/bitnami/change-password-backup.sh
fi
sed -i '/generated by/d'      /opt/bitnami/stats/agent.conf
sed -i '/installation_guid/d' /opt/bitnami/stats/agent.conf
su -l bitnami -c 'cd /opt/bitnami/stats && ./agent.bin --run -D'
if test -f /home/bitnami/change-password-backup.sh ; then
  mv /home/bitnami/change-password-backup.sh /home/bitnami/change-password.sh
fi

if [ -f "/usr/sbin/service" ]; then
  /usr/sbin/service cron restart
fi

sed -i '/agent.bin/d' /etc/crontab
echo "$MINUTE * * * * bitnami cd /opt/bitnami/stats && ./agent.bin --run -D" >> /etc/crontab

